# 监听退出的接口，即所有接口都会进行监听
spring:
  application:
    name: cas-client1
  cas:
    sign-out-filters: /*
  # 需要拦截的认证的接口
    auth-filters: /*
    validate-filters: /*
    request-wrapper-filters: /*
    assertion-filters: /*
    # 表示忽略拦截的接口，也就是不用进行拦截
    ignore-filters: /test
    cas-server-login-url: http://cas.example.org:8080/cas/login
    cas-server-url-prefix: http://cas.example.org:8080/cas/
    redirect-after-validation: true
    use-session: true
    server-name: http://localhost:8082

server:
  port: 8082